version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - "/app/node_modules"
    depends_on:
      - mysql_server
    networks:
      - app-tier

  mysql_server:
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - app-tier
    environment:
      MYSQL_DATABASE: socka
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
