version : "3.7"

services:
  mysql_application:
    container_name: mysql_application
    image: "mysql:latest"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: socka
      MYSQL_ALLOW_EMPTY_PASSWORD: null
      MYSQL_ROOT_HOST: '%'
    networks:
      - apps_network

    volumes: 
      - mysql_db:/data/db
    
  apps:
    build: .
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mysql_application
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=socka
      - MYSQL_USER=root
      - MYSQL_HOST=mysql_application
    networks:
      - apps_network

networks:
  apps_network:
    name: apps_network

volumes:
  mysql_db: {}