<<<<<<< HEAD
version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - "/app/node_modules"
    depends_on:
      - mysql_server
    networks:
      - app-tier

  mysql_server:
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - app-tier
    environment:
      MYSQL_DATABASE: socka
      MYSQL_ALLOW_EMPTY_PASSWORD: ok
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
=======
version : "3.7"

services:
  mysql:
    image: "mysql:latest"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    
  apps:
    build: .
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=socka
      - NODE_ENV=development
      - DB_HOST=localhost

volumes:
  mysql_db: {}
>>>>>>> 6c82196c6675e6b41c371c8ea4f7f47063033d50
