version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_DATABASE
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - db:/var/lib/mysql
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_dbdoc.sql
    networks:
      - app-network

  app:
    depends_on:
      - mysqldb
    build: .
    restart: always
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment:
      - WAIT_FOR_DB=true
      - DB_HOST=mysqldb
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_DATABASE
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    hostname: nginx
    ports:
        - "80:80" 
    depends_on:
        - app
    networks:
        - app-network
        
volumes:
  db:
networks:
  app-network:
    driver: bridge